/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const DemoRequest = IDL.Record({
  'teamSize' : IDL.Text,
  'name' : IDL.Text,
  'submittedAt' : IDL.Int,
  'email' : IDL.Text,
  'company' : IDL.Text,
  'preferredTime' : IDL.Text,
});
export const CustomId = IDL.Nat;

export const idlService = IDL.Service({
  'getAllDemoRequests' : IDL.Func([], [IDL.Vec(DemoRequest)], ['query']),
  'getAllDemoRequestsByEmail' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(DemoRequest)],
      ['query'],
    ),
  'submitDemoRequest' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [CustomId],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const DemoRequest = IDL.Record({
    'teamSize' : IDL.Text,
    'name' : IDL.Text,
    'submittedAt' : IDL.Int,
    'email' : IDL.Text,
    'company' : IDL.Text,
    'preferredTime' : IDL.Text,
  });
  const CustomId = IDL.Nat;
  
  return IDL.Service({
    'getAllDemoRequests' : IDL.Func([], [IDL.Vec(DemoRequest)], ['query']),
    'getAllDemoRequestsByEmail' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(DemoRequest)],
        ['query'],
      ),
    'submitDemoRequest' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [CustomId],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };