/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type CustomId = bigint;
export interface DemoRequest {
  'teamSize' : string,
  'name' : string,
  'submittedAt' : bigint,
  'email' : string,
  'company' : string,
  'preferredTime' : string,
}
export interface _SERVICE {
  'getAllDemoRequests' : ActorMethod<[], Array<DemoRequest>>,
  'getAllDemoRequestsByEmail' : ActorMethod<[string], Array<DemoRequest>>,
  'submitDemoRequest' : ActorMethod<
    [string, string, string, string, string],
    CustomId
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];